-- PLAN.md §6.2 / Phase K step 42: scheduled guest-account cleanup.
--
-- Originally: CREATE EXTENSION pg_cron + an in-Postgres cron.schedule() call
-- (see this repo's earlier commit history / project memory). That requires
-- pg_cron, which needs a self-managed Postgres instance (e.g. a Fly Postgres
-- Machine) -- NOT available on Render's managed Postgres, which is what this
-- project actually deploys to (2026-08-21 decision).
--
-- Left as a no-op (rather than deleted) so `prisma migrate deploy`'s applied
-- history stays consistent with what's already recorded for the local dev
-- database. The real mechanism is now scripts/prune-inactive-guests.ts, run
-- on a schedule by a Render Cron Job service (see render.yaml) instead of
-- inside Postgres itself -- same rule (guests inactive 30+ days), same
-- cascade-delete behavior off User.
SELECT 1;
